
run_bash_pipline: 
	./scripts/pipline.sh data/SRR33692911.fastq.gz data/ref_ecoli.fna.gz

clean:
	rm -rf results/*
	rm -rf data/ref_ecoli.fna.gz.*
	rm -rf data/SRR33692911_fastqc.zip
	rm -rf data/SRR33692911_fastqc.html
	rm -rf framework/_scipipe*
	rm -rf framework/graph
	rm -rf framework/log